export const demoObject = {
  accuracy: 0,
  allowedActions: {
    HUB_SHARE_OBJECTS: 1,
    OBJECT_CARD_EDIT: 1,
    OBJECT_CLEAR_ALARM: 1,
    OBJECT_GET_ALARMS: 1,
    OBJECT_GET_EVENTS: 1,
    OBJECT_GET_PARAMS: 1,
    OBJECT_GET_TRACK: 1,
    OBJECT_PHOTOS: 1,
    OBJECT_REMOTE_CONTROL: 1,
    OBJECT_TAKE_PHOTO: 1,
    PUSH: 1,
  },
  alt: 0,
  areas: {},
  batteryLevel: 0,
  customCode: 0,
  deviceSubtype: 0,
  deviceType: 1,
  deviceTypeId: 210,
  ignitionOn: false,
  lat: 51.169392,
  lon: 71.449074,
  myOwn: false,
  name: 'Образец',
  oid: 1,
  online: false,
  outs: {},
  owners: [
    {
      id: 266612,
    },
  ],
  photoUrl: require('../../img/example_child_photo.png'),
  props: {
    buzzerEnabled: 1,
    checkinPeriod: 3600,
    enableEcoMode: 1,
    enableGeozoneEnterAlert: 1,
    enableGeozoneLeaveAlert: 1,
    enableLowBatteryAlert: 1,
    enableRemovalSensor: 1,
    enableSmsAlert: 0,
    enableStepCounter: 0,
    imei: 'HTTP_ae956869-068e-4431-867f-a258f51fd47a',
    language: 'ru',
    photo: '8c2792ac-04a5-4224-9d0d-1098b77b0890',
    timezone: 'Etc/GMT-6',
  },
  reservePowerOn: true,
  speed: 0,
  states: {
    adminDisabledAlert: 0,
    backgroundModeAlert: 0,
    dndEnabled: 1,
    firmware: 'HTTP-1.0.19-ios-13.4.1',
    gpsEnabled: 1,
    gpsPermissionAlert: 1,
    micPermissionAlert: 0,
    mobileDataAlert: 0,
    offlineAlert: 1,
    powersavingAlert: 1,
    removedAlarm: 1,
  },
  trail: [],
  ts: 1590223996000,
  voltage: 41,
  voltageLevel: 0,
  setPosition: function (lat: number, lon: number): void {
    this.lat = lat;
    this.lon = lon;
  },
};
