export default kr = {
  intro_9: '자녀와 공통 언어 찾기',
  intro_10: '아이의 소중한 꿈을 이뤄 보세요!',
  menu_achievments: '아이의 목표 달성',
  child_dreams: '아이의 꿈들',
  task_history: '작업 기록',
  parent_tasks: '아이에게 내준 과제',
  no_task_completed: '아이가 과제를 수행하면 여기에 나올거에요!',
  child_finished_tasks: '아이가 작업을 다 했어요. 확인해 보세요!',
  ask_child_add_dream: '아이의 소중한 꿈을 보시려면 아이에게 소중한 꿈을 추가해 달라고 하세요!',
  sent_add_dream_message: '좋아요! 아이에게 자기 꿈을 추가해 달라고 했어요. 추가할 때까지 기다리면 돼요.',
  ask_child_add_dream_button_title: '아이에게 자기 꿈을 추가해 달라고 하기',
  ask_child_add_dream_message: '너의 소중한 꿈을 이뤄 주고 싶어요! 앱에 추가해 봐요 ^^',
  add_new_task: '과제 추가하기',
  add_task_dialog: '과제 추가',
  set_reward: '포상을 정해 보세요',
  points: '금전',
  confirm_task_dialog: '과제 수행을 확인하세요',
  write_praise_comment: '칭찬을 써 보세요',
  estimate_dream: '아이의 새로운 꿈',
  set_price_dream: '값을 정해 보세요',
  redeem: '이뤄 보기',
  got: '받음',
  from: '에서',
  redeemed: '이뤘음',
  estimate: '평가하기',
  decline: '취소',
  declined: '취소함',
  estimate_new_child_dream: '이의 새로운 꿈을 평가해 보세요!',
  child_dream_subtitle: '아이의 꿈들!',
  title_required: '제목은 필수!',
  no_child_finished_tasks: '아이가 과제를 수행하면 여기에 나올거에요',
  buy_premium_badge: '구독 구매하기',
  add: '추가하기',
  last_seen: '접속함',
  ago: '전',
  subsribe_for_month: '한달에 {0}으로 구독 구매하기',
  terms_of_use_url: 'https://kidsecurity.net/termsofuse',
  policy_url: 'https://kidsecurity.net/privacy_policy',
  standart: '기준',
  premium: '프리미엄',
  layer: '종류',
  child_location: '아이의 위치',
  kid_achievements: '아이의 목표 달성',
  record_sound: '아이 주위 소리 녹음하기',
  send_signal: '신호음을 소리 없음으로 보내기',
  app_statistics: '앱 통계',
  child_movement: '위치 기록',
  three_month_subheader: '한달 후에 구독 값은 3달에 {0} 됩니다',
  three_month_footer:
    '구독을 하시면 첫번째 달은 {0} 계산되고, 두번째 달부터 구독취소 할때까지 3개월에 한번 금액이 청구됩니다',
  charge: '배터리',
  accuracy: '좌표 정밀도',
  metrs: '미터',
  m: 'm',
  geo_zone_name: '위치 이름',
  try_premium2_header: '격리 기간에 절약하세요', /* todo */
  try_premium2_subheader: '주식 종료까지',
  fix: '제거하기',
  child_phone_problems: '아이 스마트폰의 문제',
  task_name: '과제 제목',
  ach_feature_title_1: '의 작업을 할 수 있습니다!',
  ach_feature_text_1: '당신의 아이에게 그것을 개발할 작업을 제공.',
  ach_feature_button_1: '더 멀리',
  ach_feature_title_2: '보상과 동기를 부여!',
  ach_feature_text_2: '자녀가 과제를 완료하도록 동기를 부여하십시오. 보상은 그가 요구 한 것일 수 있습니다.',
  ach_feature_button_2: '대박',
  ach_feature_title_3: '자녀에게 목표에 도달하도록 가르치십시오!',
  ach_feature_text_3: '작업을 완료,아이는 보상을 교환 할 수있는 동전을 축적!',
  ach_feature_button_3: ' 시작합시다!',
};
