import { Image, ImageSourcePropType } from 'react-native';
interface Sticker {
  previewPath: string;
  stickerPath: string;
  id: string;
  preview: ImageSourcePropType;
  sticker: ImageSourcePropType;
}

//because of restriction of react native we can't use template literals in definition of require cause assets loads before compilation of js so we need define whole map beforehand
export const stickers: Sticker[] = [
  {
    id: '0',
    previewPath: '../img/assets/previews/0.png',
    stickerPath: '../img/assets/stickers/0.png',
    preview: require('../img/assets/stickers/0.png'),
    sticker: require('../img/assets/stickers/0.png'),
  },
  {
    id: '1',
    previewPath: '../img/assets/previews/1.png',
    stickerPath: '../img/assets/stickers/1.png',
    preview: require('../img/assets/stickers/1.png'),
    sticker: require('../img/assets/stickers/1.png'),
  },
  {
    id: '2',
    previewPath: '../img/assets/previews/2.png',
    stickerPath: '../img/assets/stickers/2.png',
    preview: require('../img/assets/stickers/2.png'),
    sticker: require('../img/assets/stickers/2.png'),
  },
  {
    id: '3',
    previewPath: '../img/assets/previews/3.png',
    stickerPath: '../img/assets/stickers/3.png',
    preview: require('../img/assets/stickers/3.png'),
    sticker: require('../img/assets/stickers/3.png'),
  },
  {
    id: '4',
    previewPath: '../img/assets/previews/4.png',
    stickerPath: '../img/assets/stickers/4.png',
    preview: require('../img/assets/stickers/4.png'),
    sticker: require('../img/assets/stickers/4.png'),
  },
  {
    id: '5',
    previewPath: '../img/assets/previews/5.png',
    stickerPath: '../img/assets/stickers/5.png',
    preview: require('../img/assets/stickers/5.png'),
    sticker: require('../img/assets/stickers/5.png'),
  },
  {
    id: '6',
    previewPath: '../img/assets/previews/6.png',
    stickerPath: '../img/assets/stickers/6.png',
    preview: require('../img/assets/stickers/6.png'),
    sticker: require('../img/assets/stickers/6.png'),
  },
  {
    id: '7',
    previewPath: '../img/assets/previews/7.png',
    stickerPath: '../img/assets/stickers/7.png',
    preview: require('../img/assets/stickers/7.png'),
    sticker: require('../img/assets/stickers/7.png'),
  },
  {
    id: '8',
    previewPath: '../img/assets/previews/8.png',
    stickerPath: '../img/assets/stickers/8.png',
    preview: require('../img/assets/stickers/8.png'),
    sticker: require('../img/assets/stickers/8.png'),
  },
  {
    id: '9',
    previewPath: '../img/assets/previews/9.png',
    stickerPath: '../img/assets/stickers/9.png',
    preview: require('../img/assets/stickers/9.png'),
    sticker: require('../img/assets/stickers/9.png'),
  },
  {
    id: '10',
    previewPath: '../img/assets/previews/10.png',
    stickerPath: '../img/assets/stickers/10.png',
    preview: require('../img/assets/stickers/10.png'),
    sticker: require('../img/assets/stickers/10.png'),
  },
  {
    id: '11',
    previewPath: '../img/assets/previews/11.png',
    stickerPath: '../img/assets/stickers/11.png',
    preview: require('../img/assets/stickers/11.png'),
    sticker: require('../img/assets/stickers/11.png'),
  },
  {
    id: '12',
    previewPath: '../img/assets/previews/12.png',
    stickerPath: '../img/assets/stickers/12.png',
    preview: require('../img/assets/stickers/12.png'),
    sticker: require('../img/assets/stickers/12.png'),
  },
  {
    id: '13',
    previewPath: '../img/assets/previews/13.png',
    stickerPath: '../img/assets/stickers/13.png',
    preview: require('../img/assets/stickers/13.png'),
    sticker: require('../img/assets/stickers/13.png'),
  },
  {
    id: '14',
    previewPath: '../img/assets/previews/14.png',
    stickerPath: '../img/assets/stickers/14.png',
    preview: require('../img/assets/stickers/14.png'),
    sticker: require('../img/assets/stickers/14.png'),
  },
  {
    id: '15',
    previewPath: '../img/assets/previews/15.png',
    stickerPath: '../img/assets/stickers/15.png',
    preview: require('../img/assets/stickers/15.png'),
    sticker: require('../img/assets/stickers/15.png'),
  },
  {
    id: '16',
    previewPath: '../img/assets/previews/16.png',
    stickerPath: '../img/assets/stickers/16.png',
    preview: require('../img/assets/stickers/16.png'),
    sticker: require('../img/assets/stickers/16.png'),
  },
  {
    id: '17',
    previewPath: '../img/assets/previews/17.png',
    stickerPath: '../img/assets/stickers/17.png',
    preview: require('../img/assets/stickers/17.png'),
    sticker: require('../img/assets/stickers/17.png'),
  },
  {
    id: '18',
    previewPath: '../img/assets/previews/18.png',
    stickerPath: '../img/assets/stickers/18.png',
    preview: require('../img/assets/stickers/18.png'),
    sticker: require('../img/assets/stickers/18.png'),
  },
  {
    id: '19',
    previewPath: '../img/assets/previews/19.png',
    stickerPath: '../img/assets/stickers/19.png',
    preview: require('../img/assets/stickers/19.png'),
    sticker: require('../img/assets/stickers/19.png'),
  },
  {
    id: '20',
    previewPath: '../img/assets/previews/20.png',
    stickerPath: '../img/assets/stickers/20.png',
    preview: require('../img/assets/stickers/20.png'),
    sticker: require('../img/assets/stickers/20.png'),
  },
  {
    id: '21',
    previewPath: '../img/assets/previews/21.png',
    stickerPath: '../img/assets/stickers/21.png',
    preview: require('../img/assets/stickers/21.png'),
    sticker: require('../img/assets/stickers/21.png'),
  },
  {
    id: '22',
    previewPath: '../img/assets/previews/22.png',
    stickerPath: '../img/assets/stickers/22.png',
    preview: require('../img/assets/stickers/22.png'),
    sticker: require('../img/assets/stickers/22.png'),
  },
  {
    id: '23',
    previewPath: '../img/assets/previews/23.png',
    stickerPath: '../img/assets/stickers/23.png',
    preview: require('../img/assets/stickers/23.png'),
    sticker: require('../img/assets/stickers/23.png'),
  },
  {
    id: '24',
    previewPath: '../img/assets/previews/24.png',
    stickerPath: '../img/assets/stickers/24.png',
    preview: require('../img/assets/stickers/24.png'),
    sticker: require('../img/assets/stickers/24.png'),
  },
  {
    id: '25',
    previewPath: '../img/assets/previews/25.png',
    stickerPath: '../img/assets/stickers/25.png',
    preview: require('../img/assets/stickers/25.png'),
    sticker: require('../img/assets/stickers/25.png'),
  },
  {
    id: '26',
    previewPath: '../img/assets/previews/26.png',
    stickerPath: '../img/assets/stickers/26.png',
    preview: require('../img/assets/stickers/26.png'),
    sticker: require('../img/assets/stickers/26.png'),
  },
  {
    id: '27',
    previewPath: '../img/assets/previews/27.png',
    stickerPath: '../img/assets/stickers/27.png',
    preview: require('../img/assets/stickers/27.png'),
    sticker: require('../img/assets/stickers/27.png'),
  },
  {
    id: '28',
    previewPath: '../img/assets/previews/28.png',
    stickerPath: '../img/assets/stickers/28.png',
    preview: require('../img/assets/stickers/28.png'),
    sticker: require('../img/assets/stickers/28.png'),
  },
  {
    id: '29',
    previewPath: '../img/assets/previews/29.png',
    stickerPath: '../img/assets/stickers/29.png',
    preview: require('../img/assets/stickers/29.png'),
    sticker: require('../img/assets/stickers/29.png'),
  },
  {
    id: '30',
    previewPath: '../img/assets/previews/30.png',
    stickerPath: '../img/assets/stickers/30.png',
    preview: require('../img/assets/stickers/30.png'),
    sticker: require('../img/assets/stickers/30.png'),
  },
  {
    id: '31',
    previewPath: '../img/assets/previews/31.png',
    stickerPath: '../img/assets/stickers/31.png',
    preview: require('../img/assets/stickers/31.png'),
    sticker: require('../img/assets/stickers/31.png'),
  },
  {
    id: '32',
    previewPath: '../img/assets/previews/32.png',
    stickerPath: '../img/assets/stickers/32.png',
    preview: require('../img/assets/stickers/32.png'),
    sticker: require('../img/assets/stickers/32.png'),
  },
  {
    id: '33',
    previewPath: '../img/assets/previews/33.png',
    stickerPath: '../img/assets/stickers/33.png',
    preview: require('../img/assets/stickers/33.png'),
    sticker: require('../img/assets/stickers/33.png'),
  },
  {
    id: '34',
    previewPath: '../img/assets/previews/34.png',
    stickerPath: '../img/assets/stickers/34.png',
    preview: require('../img/assets/stickers/34.png'),
    sticker: require('../img/assets/stickers/34.png'),
  },
  {
    id: '35',
    previewPath: '../img/assets/previews/35.png',
    stickerPath: '../img/assets/stickers/35.png',
    preview: require('../img/assets/stickers/35.png'),
    sticker: require('../img/assets/stickers/35.png'),
  },
  {
    id: '36',
    previewPath: '../img/assets/previews/36.png',
    stickerPath: '../img/assets/stickers/36.png',
    preview: require('../img/assets/stickers/36.png'),
    sticker: require('../img/assets/stickers/36.png'),
  },
  {
    id: '37',
    previewPath: '../img/assets/previews/37.png',
    stickerPath: '../img/assets/stickers/37.png',
    preview: require('../img/assets/stickers/37.png'),
    sticker: require('../img/assets/stickers/37.png'),
  },
  {
    id: '38',
    previewPath: '../img/assets/previews/38.png',
    stickerPath: '../img/assets/stickers/38.png',
    preview: require('../img/assets/stickers/38.png'),
    sticker: require('../img/assets/stickers/38.png'),
  },
  {
    id: '39',
    previewPath: '../img/assets/previews/39.png',
    stickerPath: '../img/assets/stickers/39.png',
    preview: require('../img/assets/stickers/39.png'),
    sticker: require('../img/assets/stickers/39.png'),
  },
  {
    id: '40',
    previewPath: '../img/assets/previews/40.png',
    stickerPath: '../img/assets/stickers/40.png',
    preview: require('../img/assets/stickers/40.png'),
    sticker: require('../img/assets/stickers/40.png'),
  },
  {
    id: '41',
    previewPath: '../img/assets/previews/41.png',
    stickerPath: '../img/assets/stickers/41.png',
    preview: require('../img/assets/stickers/41.png'),
    sticker: require('../img/assets/stickers/41.png'),
  },
  {
    id: '42',
    previewPath: '../img/assets/previews/42.png',
    stickerPath: '../img/assets/stickers/42.png',
    preview: require('../img/assets/stickers/42.png'),
    sticker: require('../img/assets/stickers/42.png'),
  },
  {
    id: '43',
    previewPath: '../img/assets/previews/43.png',
    stickerPath: '../img/assets/stickers/43.png',
    preview: require('../img/assets/stickers/43.png'),
    sticker: require('../img/assets/stickers/43.png'),
  },
  {
    id: '44',
    previewPath: '../img/assets/previews/44.png',
    stickerPath: '../img/assets/stickers/44.png',
    preview: require('../img/assets/stickers/44.png'),
    sticker: require('../img/assets/stickers/44.png'),
  },
  {
    id: '45',
    previewPath: '../img/assets/previews/45.png',
    stickerPath: '../img/assets/stickers/45.png',
    preview: require('../img/assets/stickers/45.png'),
    sticker: require('../img/assets/stickers/45.png'),
  },
  {
    id: '46',
    previewPath: '../img/assets/previews/46.png',
    stickerPath: '../img/assets/stickers/46.png',
    preview: require('../img/assets/stickers/46.png'),
    sticker: require('../img/assets/stickers/46.png'),
  },
  {
    id: '47',
    previewPath: '../img/assets/previews/47.png',
    stickerPath: '../img/assets/stickers/47.png',
    preview: require('../img/assets/stickers/47.png'),
    sticker: require('../img/assets/stickers/47.png'),
  },
  {
    id: '48',
    previewPath: '../img/assets/previews/48.png',
    stickerPath: '../img/assets/stickers/48.png',
    preview: require('../img/assets/stickers/48.png'),
    sticker: require('../img/assets/stickers/48.png'),
  },
  {
    id: '49',
    previewPath: '../img/assets/previews/49.png',
    stickerPath: '../img/assets/stickers/49.png',
    preview: require('../img/assets/stickers/49.png'),
    sticker: require('../img/assets/stickers/49.png'),
  },
  {
    id: '50',
    previewPath: '../img/assets/previews/50.png',
    stickerPath: '../img/assets/stickers/50.png',
    preview: require('../img/assets/stickers/50.png'),
    sticker: require('../img/assets/stickers/50.png'),
  },
  {
    id: '51',
    previewPath: '../img/assets/previews/51.png',
    stickerPath: '../img/assets/stickers/51.png',
    preview: require('../img/assets/stickers/51.png'),
    sticker: require('../img/assets/stickers/51.png'),
  },
  {
    id: '52',
    previewPath: '../img/assets/previews/52.png',
    stickerPath: '../img/assets/stickers/52.png',
    preview: require('../img/assets/stickers/52.png'),
    sticker: require('../img/assets/stickers/52.png'),
  },
  {
    id: '53',
    previewPath: '../img/assets/previews/53.png',
    stickerPath: '../img/assets/stickers/53.png',
    preview: require('../img/assets/stickers/53.png'),
    sticker: require('../img/assets/stickers/53.png'),
  },
  {
    id: '54',
    previewPath: '../img/assets/previews/54.png',
    stickerPath: '../img/assets/stickers/54.png',
    preview: require('../img/assets/stickers/54.png'),
    sticker: require('../img/assets/stickers/54.png'),
  },
  {
    id: '55',
    previewPath: '../img/assets/previews/55.png',
    stickerPath: '../img/assets/stickers/55.png',
    preview: require('../img/assets/stickers/55.png'),
    sticker: require('../img/assets/stickers/55.png'),
  },
  {
    id: '56',
    previewPath: '../img/assets/previews/56.png',
    stickerPath: '../img/assets/stickers/56.png',
    preview: require('../img/assets/stickers/56.png'),
    sticker: require('../img/assets/stickers/56.png'),
  },
  {
    id: '57',
    previewPath: '../img/assets/previews/57.png',
    stickerPath: '../img/assets/stickers/57.png',
    preview: require('../img/assets/stickers/57.png'),
    sticker: require('../img/assets/stickers/57.png'),
  },
  {
    id: '58',
    previewPath: '../img/assets/previews/58.png',
    stickerPath: '../img/assets/stickers/58.png',
    preview: require('../img/assets/stickers/58.png'),
    sticker: require('../img/assets/stickers/58.png'),
  },
  {
    id: '59',
    previewPath: '../img/assets/previews/59.png',
    stickerPath: '../img/assets/stickers/59.png',
    preview: require('../img/assets/stickers/59.png'),
    sticker: require('../img/assets/stickers/59.png'),
  },
  {
    id: '60',
    previewPath: '../img/assets/previews/60.png',
    stickerPath: '../img/assets/stickers/60.png',
    preview: require('../img/assets/stickers/60.png'),
    sticker: require('../img/assets/stickers/60.png'),
  },
  {
    id: '61',
    previewPath: '../img/assets/previews/61.png',
    stickerPath: '../img/assets/stickers/61.png',
    preview: require('../img/assets/stickers/61.png'),
    sticker: require('../img/assets/stickers/61.png'),
  },
  {
    id: '62',
    previewPath: '../img/assets/previews/62.png',
    stickerPath: '../img/assets/stickers/62.png',
    preview: require('../img/assets/stickers/62.png'),
    sticker: require('../img/assets/stickers/62.png'),
  },
  {
    id: '63',
    previewPath: '../img/assets/previews/63.png',
    stickerPath: '../img/assets/stickers/63.png',
    preview: require('../img/assets/stickers/63.png'),
    sticker: require('../img/assets/stickers/63.png'),
  },
  {
    id: '64',
    previewPath: '../img/assets/previews/64.png',
    stickerPath: '../img/assets/stickers/64.png',
    preview: require('../img/assets/stickers/64.png'),
    sticker: require('../img/assets/stickers/64.png'),
  },
];
